version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=file:/data/dev.db
      - LOG_LEVEL=info
    volumes:
      - db_data:/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
    driver: local 