version: '3.8'

networks:
  proxy:
    external: true

services:
  cattrack:
    container_name: cattrack
    build: .
    ports:
      - "2137:3000"
    environment:
      - DATABASE_URL=file:/data/dev.db
      - LOG_LEVEL=info
    volumes:
      - cat_db:/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cattrack.rule=Host(`cattrack.local.{DOMAINNAME}`, `cattrack.local.${HOST_SUBDOMAIN}.{DOMAINNAME}`, `cattrack.${HOST_SUBDOMAIN}.{DOMAINNAME}`, `cattrack.{DOMAINNAME}`)"
      - "traefik.http.routers.cattrack.entrypoints=https"
      - "traefik.http.routers.cattrack.tls=true"
      - "traefik.http.services.cattrack.loadbalancer.server.port=3000"

volumes:
  cat_db:
    driver: local 