/**
 * Convenience aliases over the generated OpenAPI schema types.
 *
 * `types.gen.ts` is regenerated by `pnpm gen:api`; import domain types from here
 * so the rest of the app never reaches into `components["schemas"][...]` directly.
 */
import type { components } from './types.gen'

type Schemas = components['schemas']

export type FoodType = Schemas['FoodType']
export type CalorieBasis = Schemas['CalorieBasis']

export type Food = Schemas['FoodResponse']
export type FoodCreate = Schemas['FoodCreate']
export type FoodUpdate = Schemas['FoodUpdate']
export type FoodDeleteResult = Schemas['FoodDeleteResult']

export type Cat = Schemas['CatResponse']
export type CatCreate = Schemas['CatCreate']
export type CatUpdate = Schemas['CatUpdate']

export type Weight = Schemas['WeightResponse']
export type WeightCreate = Schemas['WeightCreate']

export type Meal = Schemas['MealResponse']
export type MealCreate = Schemas['MealCreate']
export type MealUpdate = Schemas['MealUpdate']

export type Settings = Schemas['SettingsResponse']
export type SettingsUpdate = Schemas['SettingsUpdate']
