/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cats */
        get: operations["list_cats_api_cats_get"];
        put?: never;
        /** Create Cat */
        post: operations["create_cat_api_cats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cats/{cat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cat */
        get: operations["get_cat_api_cats__cat_id__get"];
        put?: never;
        post?: never;
        /** Delete Cat */
        delete: operations["delete_cat_api_cats__cat_id__delete"];
        options?: never;
        head?: never;
        /** Update Cat */
        patch: operations["update_cat_api_cats__cat_id__patch"];
        trace?: never;
    };
    "/api/cats/{cat_id}/weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Weights */
        get: operations["list_weights_api_cats__cat_id__weights_get"];
        put?: never;
        /** Upsert Weight */
        post: operations["upsert_weight_api_cats__cat_id__weights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cats/{cat_id}/weights/{measured_on}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Weight */
        delete: operations["delete_weight_api_cats__cat_id__weights__measured_on__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Foods */
        get: operations["list_foods_api_foods_get"];
        put?: never;
        /** Create Food */
        post: operations["create_food_api_foods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/{food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Food */
        delete: operations["delete_food_api_foods__food_id__delete"];
        options?: never;
        head?: never;
        /** Update Food */
        patch: operations["update_food_api_foods__food_id__patch"];
        trace?: never;
    };
    "/api/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meals */
        get: operations["list_meals_api_meals_get"];
        put?: never;
        /** Create Meal */
        post: operations["create_meal_api_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meal Suggestions */
        get: operations["meal_suggestions_api_meals_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Meal */
        delete: operations["delete_meal_api_meals__meal_id__delete"];
        options?: never;
        head?: never;
        /** Update Meal */
        patch: operations["update_meal_api_meals__meal_id__patch"];
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today */
        get: operations["today_api_reports_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Range Report */
        get: operations["range_report_api_reports_range_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comparison */
        get: operations["comparison_api_reports_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/target-suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Target Suggestion */
        get: operations["target_suggestion_api_target_suggestion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CalorieBasis
         * @enum {string}
         */
        CalorieBasis: "PER_100G" | "PER_PIECE";
        /** CatComparison */
        CatComparison: {
            /** Cat Id */
            cat_id: number;
            /** Cat Name */
            cat_name: string;
            /** Avg Kcal Per Day */
            avg_kcal_per_day: number;
            /** Target Kcal */
            target_kcal: number;
            /** Adherence Pct */
            adherence_pct: number;
        };
        /** CatCreate */
        CatCreate: {
            /** Name */
            name: string;
            /** Target Kcal */
            target_kcal: number;
            /** Goal Weight Kg */
            goal_weight_kg?: number | null;
            /** Default Wet Food Id */
            default_wet_food_id?: number | null;
            /** Default Dry Food Id */
            default_dry_food_id?: number | null;
            /** Initial Weight Kg */
            initial_weight_kg?: number | null;
        };
        /** CatResponse */
        CatResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Target Kcal */
            target_kcal: number;
            /** Goal Weight Kg */
            goal_weight_kg: number | null;
            /** Default Wet Food Id */
            default_wet_food_id: number | null;
            /** Default Dry Food Id */
            default_dry_food_id: number | null;
            /** Current Weight Kg */
            current_weight_kg: number | null;
            /** Meal Count */
            meal_count: number;
        };
        /**
         * CatTodayReport
         * @description One cat's calorie standing for the current household-local day.
         */
        CatTodayReport: {
            /** Cat Id */
            cat_id: number;
            /** Cat Name */
            cat_name: string;
            /** Target Kcal */
            target_kcal: number;
            /** Consumed Kcal */
            consumed_kcal: number;
            /** Remaining Kcal */
            remaining_kcal: number;
            /** Over */
            over: boolean;
            /** Grams Equivalents */
            grams_equivalents: components["schemas"]["DefaultFoodGrams"][];
            /** Portion Suggestions */
            portion_suggestions: components["schemas"]["DefaultFoodGrams"][];
        };
        /** CatUpdate */
        CatUpdate: {
            /** Name */
            name?: string | null;
            /** Target Kcal */
            target_kcal?: number | null;
            /** Goal Weight Kg */
            goal_weight_kg?: number | null;
            /** Default Wet Food Id */
            default_wet_food_id?: number | null;
            /** Default Dry Food Id */
            default_dry_food_id?: number | null;
        };
        /** ComparisonReport */
        ComparisonReport: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Timezone */
            timezone: string;
            /** Cats */
            cats: components["schemas"]["CatComparison"][];
        };
        /**
         * DailyKcalPoint
         * @description Consumed kcal for one household-local day (zero-filled across the range).
         */
        DailyKcalPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Kcal */
            kcal: number;
        };
        /**
         * DefaultFoodGrams
         * @description A grams figure tied to one of a cat's default foods.
         *
         *     Used for both the remaining-kcal grams-equivalent and the per-meal portion
         *     suggestion. Only produced for non-archived ``PER_100G`` default foods
         *     (grams are meaningless for per-piece foods). ``food_type`` is ``WET`` or
         *     ``DRY`` — it says which default the figure belongs to.
         */
        DefaultFoodGrams: {
            /** Food Id */
            food_id: number;
            /** Food Name */
            food_name: string;
            food_type: components["schemas"]["FoodType"];
            /** Grams */
            grams: number;
        };
        /** FoodCreate */
        FoodCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["FoodType"];
            calorie_basis: components["schemas"]["CalorieBasis"];
            /** Kcal Per Basis */
            kcal_per_basis: number;
            /**
             * Set Default For All Cats
             * @default false
             */
            set_default_for_all_cats: boolean;
        };
        /**
         * FoodDeleteResult
         * @description Outcome of ``DELETE /foods/{id}``.
         *
         *     ``archived`` is true when meals referenced the food (soft-deleted, ``food``
         *     populated); false when it was hard-deleted (``food`` null).
         *     ``cleared_default_for_cat_ids`` lets the UI warn which cats lost a default.
         */
        FoodDeleteResult: {
            /** Archived */
            archived: boolean;
            food: components["schemas"]["FoodResponse"] | null;
            /** Cleared Default For Cat Ids */
            cleared_default_for_cat_ids: number[];
        };
        /**
         * FoodMutationResult
         * @description Outcome of ``POST /foods`` and ``PATCH /foods/{id}``.
         *
         *     ``defaulted_for_cat_count`` is the number of cats whose matching default was
         *     pointed at this food by ``set_default_for_all_cats`` (0 when the flag was
         *     not set), so the UI can say "set as default for N cats".
         */
        FoodMutationResult: {
            food: components["schemas"]["FoodResponse"];
            /** Defaulted For Cat Count */
            defaulted_for_cat_count: number;
        };
        /** FoodResponse */
        FoodResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            type: components["schemas"]["FoodType"];
            calorie_basis: components["schemas"]["CalorieBasis"];
            /** Kcal Per Basis */
            kcal_per_basis: number;
            /** Archived At */
            archived_at: string | null;
        };
        /**
         * FoodType
         * @enum {string}
         */
        FoodType: "WET" | "DRY" | "TREAT";
        /** FoodUpdate */
        FoodUpdate: {
            /** Name */
            name?: string | null;
            calorie_basis?: components["schemas"]["CalorieBasis"] | null;
            /** Kcal Per Basis */
            kcal_per_basis?: number | null;
            type?: components["schemas"]["FoodType"] | null;
            /**
             * Set Default For All Cats
             * @default false
             */
            set_default_for_all_cats: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** MealCreate */
        MealCreate: {
            /** Cat Id */
            cat_id: number;
            /** Food Id */
            food_id: number;
            /** Quantity */
            quantity: number;
            /** Fed At */
            fed_at?: string | null;
        };
        /** MealResponse */
        MealResponse: {
            /** Id */
            id: number;
            /** Cat Id */
            cat_id: number;
            /** Food Id */
            food_id: number;
            /** Food Name */
            food_name: string;
            /** Quantity */
            quantity: number;
            basis: components["schemas"]["CalorieBasis"];
            /** Kcal Per Basis */
            kcal_per_basis: number;
            /** Kcal */
            kcal: number;
            /**
             * Fed At
             * Format: date-time
             */
            fed_at: string;
        };
        /**
         * MealSuggestion
         * @description A proposed one-tap meal to re-log.
         *
         *     ``kcal`` is derived at the food's *current* values (a proposal, not a
         *     historical snapshot); logging it creates a fresh snapshot.
         */
        MealSuggestion: {
            /** Food Id */
            food_id: number;
            /** Food Name */
            food_name: string;
            food_type: components["schemas"]["FoodType"];
            /** Quantity */
            quantity: number;
            basis: components["schemas"]["CalorieBasis"];
            /** Kcal */
            kcal: number;
        };
        /** MealUpdate */
        MealUpdate: {
            /** Cat Id */
            cat_id?: number | null;
            /** Food Id */
            food_id?: number | null;
            /** Quantity */
            quantity?: number | null;
            /** Fed At */
            fed_at?: string | null;
        };
        /**
         * PortionHistoryPoint
         * @description A single grams-measured meal for the portion-history chart.
         *
         *     Only ``PER_100G`` ``WET``/``DRY`` meals appear here; treats and per-piece
         *     meals are excluded (pieces are not grams) though they still count in all
         *     kcal totals.
         */
        PortionHistoryPoint: {
            /**
             * Fed At
             * Format: date-time
             */
            fed_at: string;
            /** Grams */
            grams: number;
            food_type: components["schemas"]["FoodType"];
        };
        /**
         * RangeReport
         * @description Everything the History page needs for one cat in one round trip.
         */
        RangeReport: {
            /** Cat Id */
            cat_id: number;
            /** Cat Name */
            cat_name: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Timezone */
            timezone: string;
            /** Target Kcal */
            target_kcal: number;
            /** Daily Kcal */
            daily_kcal: components["schemas"]["DailyKcalPoint"][];
            /** Avg Kcal Per Day */
            avg_kcal_per_day: number;
            /** Trend Pct */
            trend_pct: number | null;
            /** Timing Pattern */
            timing_pattern: number[][];
            /** Portion History */
            portion_history: components["schemas"]["PortionHistoryPoint"][];
            /** Weight Series */
            weight_series: components["schemas"]["WeightPoint"][];
            /** Goal Weight Kg */
            goal_weight_kg: number | null;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Timezone */
            timezone: string;
            /** Portion Suggestions Enabled */
            portion_suggestions_enabled: boolean;
            /** Meals Per Day */
            meals_per_day: number;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Timezone */
            timezone: string;
            /** Portion Suggestions Enabled */
            portion_suggestions_enabled: boolean;
            /** Meals Per Day */
            meals_per_day: number;
        };
        /**
         * TargetBasis
         * @description Which weight the RER is computed from.
         * @enum {string}
         */
        TargetBasis: "GOAL_WEIGHT" | "CURRENT_WEIGHT";
        /**
         * TargetSuggestionResponse
         * @description RER/MER breakdown for the calculator dialog (always a suggestion).
         *
         *     ``rer_kcal = 70 x basis_weight ** 0.75`` where the basis weight is the goal
         *     weight (factor 0.8, weight loss) when a goal is set, otherwise the current
         *     weight (factor 1.2, neutered-adult maintenance).
         *     ``suggested_target_kcal = rer_kcal x factor``.
         *
         *     ``cat_id`` is null in the by-weight mode (onboarding a cat that does not
         *     exist yet), where the weights come straight from the query params.
         */
        TargetSuggestionResponse: {
            /** Cat Id */
            cat_id: number | null;
            /** Current Weight Kg */
            current_weight_kg: number | null;
            /** Goal Weight Kg */
            goal_weight_kg: number | null;
            /** Rer Kcal */
            rer_kcal: number;
            /** Factor */
            factor: number;
            basis: components["schemas"]["TargetBasis"];
            /** Suggested Target Kcal */
            suggested_target_kcal: number;
        };
        /** TodayReport */
        TodayReport: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Timezone */
            timezone: string;
            /** Cats */
            cats: components["schemas"]["CatTodayReport"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightCreate */
        WeightCreate: {
            /** Weight Kg */
            weight_kg: number;
            /**
             * Measured On
             * Format: date
             */
            measured_on: string;
        };
        /** WeightPoint */
        WeightPoint: {
            /**
             * Measured On
             * Format: date
             */
            measured_on: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /** WeightResponse */
        WeightResponse: {
            /** Id */
            id: number;
            /** Cat Id */
            cat_id: number;
            /** Weight Kg */
            weight_kg: number;
            /**
             * Measured On
             * Format: date
             */
            measured_on: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_cats_api_cats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatResponse"][];
                };
            };
        };
    };
    create_cat_api_cats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cat_api_cats__cat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cat_api_cats__cat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cat_api_cats__cat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_weights_api_cats__cat_id__weights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_weight_api_cats__cat_id__weights_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeightCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_weight_api_cats__cat_id__weights__measured_on__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
                measured_on: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_foods_api_foods_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_food_api_foods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodMutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_food_api_foods__food_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_food_api_foods__food_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodMutationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meals_api_meals_get: {
        parameters: {
            query?: {
                cat_id?: number | null;
                start?: string | null;
                end?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_api_meals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meal_suggestions_api_meals_suggestions_get: {
        parameters: {
            query: {
                cat_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_api_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_api_meals__meal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_api_reports_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayReport"];
                };
            };
        };
    };
    range_report_api_reports_range_get: {
        parameters: {
            query: {
                cat_id: number;
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comparison_api_reports_comparison_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    target_suggestion_api_target_suggestion_get: {
        parameters: {
            query?: {
                cat_id?: number | null;
                weight_kg?: number | null;
                goal_weight_kg?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetSuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
